"""
Configuration Persistence & Backup Manager for Tool-Klipper-Calibration.

Safely saves calibrated tool offsets into an isolated tool_offsets.cfg file
using atomic temporary writes and automatic timestamped backups.
"""

from typing import Dict, List, Optional, Any
import datetime
import glob
import logging
import os
import re
import shutil

logger = logging.getLogger("tool_calibrator.config_manager")


class ConfigManagerException(Exception):
    """Raised when configuration operations fail."""
    pass


class ConfigManager:
    """
    Manages offset reading, atomic persistence, and historical rollbacks.
    """

    def __init__(self, config_file_path: str = "~/printer_data/config/tool_offsets.cfg") -> None:
        self.config_path = os.path.expanduser(config_file_path)
        self.max_backups = 10

    def create_backup(self) -> Optional[str]:
        """
        Creates a timestamped backup copy of tool_offsets.cfg if it exists.
        Automatically rotates and purges backups older than max_backups.
        """
        if not os.path.exists(self.config_path):
            return None

        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S_%f")
        backup_filename = f"{self.config_path}.calib_backup_{timestamp}"
        try:
            shutil.copy2(self.config_path, backup_filename)
            logger.info(f"Created configuration backup: {backup_filename}")
            self._rotate_backups()
            return backup_filename
        except Exception as ex:
            logger.error(f"Failed to create configuration backup: {ex}")
            raise ConfigManagerException(f"Backup creation failed: {ex}")

    def _rotate_backups(self) -> None:
        """Keeps the most recent N backups and deletes older ones."""
        pattern = f"{self.config_path}.calib_backup_*"
        backups = sorted(glob.glob(pattern))
        if len(backups) > self.max_backups:
            to_remove = backups[:-self.max_backups]
            for old_backup in to_remove:
                try:
                    os.remove(old_backup)
                    logger.debug(f"Purged old backup: {old_backup}")
                except OSError:
                    pass

    def load_section(self, section_name: str) -> Dict[str, str]:
        """
        Loads key-value pairs from a specific section in tool_offsets.cfg.
        Returns an empty dict if the section or file does not exist.
        """
        if not os.path.exists(self.config_path):
            return {}

        clean_section = section_name.strip("[]")
        target_header = f"[{clean_section}]"
        results: Dict[str, str] = {}
        in_section = False

        with open(self.config_path, "r", encoding="utf-8") as f:
            for raw_line in f:
                line = raw_line.strip()
                if line.startswith("[") and line.endswith("]"):
                    in_section = (line == target_header)
                    continue

                if in_section and line and not line.startswith("#"):
                    if ":" in line:
                        k, v = line.split(":", 1)
                        results[k.strip()] = v.strip()
                    elif "=" in line:
                        k, v = line.split("=", 1)
                        results[k.strip()] = v.strip()

        return results

    def save_section(self, section_name: str, values: Dict[str, Any]) -> None:
        """
        Atomically updates or creates any [section_name] with key-value pairs.
        Ignores None values to prevent writing invalid config lines.
        """
        self.create_backup()

        lines: List[str] = []
        if os.path.exists(self.config_path):
            with open(self.config_path, "r", encoding="utf-8") as f:
                lines = f.readlines()
        else:
            lines = [
                "# Tool-Klipper-Calibration Offsets File\n",
                "# Auto-generated by Tool-Klipper-Calibration\n",
                "# Include this in printer.cfg via: [include tool_offsets.cfg]\n\n"
            ]

        clean_section = section_name.strip("[]")
        target_header = f"[{clean_section}]"
        section_start = -1
        section_end = len(lines)

        m_tool = re.match(r"^tool\s+(?:t)?(\d+)$", clean_section, re.IGNORECASE)
        tool_pattern = re.compile(rf"^\[tool\s+(?:t)?{m_tool.group(1)}\]$", re.IGNORECASE) if m_tool else None

        for i, raw_line in enumerate(lines):
            line = raw_line.strip()
            if (tool_pattern and tool_pattern.match(line)) or line == target_header:
                section_start = i
                target_header = line
            elif section_start != -1 and line.startswith("[") and line.endswith("]"):
                section_end = i
                break

        formatted_values = {}
        high_precision_keys = {"mpp", "matrix_a", "matrix_b", "matrix_c", "matrix_d", "matrix_tx", "matrix_ty"}
        for k, v in values.items():
            if v is None:
                continue
            if isinstance(v, float):
                if k in high_precision_keys or "matrix" in k:
                    formatted_values[k] = f"{v:.6f}"
                else:
                    formatted_values[k] = f"{v:.4f}"
            else:
                formatted_values[k] = str(v)

        if not formatted_values:
            return

        if section_start != -1:
            existing_keys = set()
            for idx in range(section_start + 1, section_end):
                line = lines[idx].strip()
                if not line or line.startswith("#"):
                    continue
                delimiter = ":" if ":" in line else "=" if "=" in line else None
                if delimiter:
                    found_key = line.split(delimiter, 1)[0].strip()
                    if found_key in formatted_values:
                        lines[idx] = f"{found_key}: {formatted_values[found_key]}\n"
                        existing_keys.add(found_key)

            missing_keys = [k for k in formatted_values if k not in existing_keys]
            if missing_keys:
                insert_lines = [f"{k}: {formatted_values[k]}\n" for k in missing_keys]
                lines[section_end:section_end] = insert_lines
        else:
            new_block = [f"\n{target_header}\n"]
            for k, val_str in formatted_values.items():
                new_block.append(f"{k}: {val_str}\n")
            lines.extend(new_block)

        tmp_path = f"{self.config_path}.tmp"
        try:
            with open(tmp_path, "w", encoding="utf-8") as f:
                f.writelines(lines)
                f.flush()
                os.fsync(f.fileno())

            os.replace(tmp_path, self.config_path)
            logger.info(f"Successfully committed section {target_header} to {self.config_path}")
        except Exception as ex:
            if os.path.exists(tmp_path):
                os.remove(tmp_path)
            raise ConfigManagerException(f"Failed to atomically write config: {ex}")

    def save_tool_offsets(self, tool_number: int, offsets: Dict[str, float]) -> None:
        """
        Atomically updates or creates the [tool N] section with new gcode offsets.
        """
        offset_strings = {}
        for axis, val in offsets.items():
            if val is not None:
                offset_strings[f"gcode_{axis.lower()}_offset"] = val

        self.save_section(f"tool {tool_number}", offset_strings)

    def save_all_tool_offsets(self, results: Dict[int, Dict[str, float]]) -> None:
        """
        Atomically updates all [tool N] sections in a single file transaction,
        creating exactly one timestamped backup for the entire calibration session.
        """
        self.create_backup()

        lines: List[str] = []
        if os.path.exists(self.config_path):
            with open(self.config_path, "r", encoding="utf-8") as f:
                lines = f.readlines()
        else:
            lines = [
                "# Tool-Klipper-Calibration Offsets File\n",
                "# Auto-generated by Tool-Klipper-Calibration\n",
                "# Include this in printer.cfg via: [include tool_offsets.cfg]\n\n"
            ]

        for t_num, offsets in sorted(results.items()):
            if not offsets:
                continue
            clean_section = f"tool {t_num}"
            target_header = f"[{clean_section}]"
            section_start = -1
            section_end = len(lines)

            tool_pattern = re.compile(rf"^\[tool\s+(?:t)?{t_num}\]$", re.IGNORECASE)

            for i, raw_line in enumerate(lines):
                line = raw_line.strip()
                if tool_pattern.match(line) or line == target_header:
                    section_start = i
                    target_header = line
                elif section_start != -1 and line.startswith("[") and line.endswith("]"):
                    section_end = i
                    break

            formatted_values = {}
            for axis, val in offsets.items():
                if val is not None:
                    formatted_values[f"gcode_{axis.lower()}_offset"] = f"{val:.4f}"

            if not formatted_values:
                continue

            if section_start != -1:
                existing_keys = set()
                for idx in range(section_start + 1, section_end):
                    line = lines[idx].strip()
                    if not line or line.startswith("#"):
                        continue
                    delimiter = ":" if ":" in line else "=" if "=" in line else None
                    if delimiter:
                        found_key = line.split(delimiter, 1)[0].strip()
                        if found_key in formatted_values:
                            lines[idx] = f"{found_key}: {formatted_values[found_key]}\n"
                            existing_keys.add(found_key)

                missing_keys = [k for k in formatted_values if k not in existing_keys]
                if missing_keys:
                    insert_lines = [f"{k}: {formatted_values[k]}\n" for k in missing_keys]
                    lines[section_end:section_end] = insert_lines
            else:
                new_block = [f"\n{target_header}\n"]
                for k, val_str in formatted_values.items():
                    new_block.append(f"{k}: {val_str}\n")
                lines.extend(new_block)

        tmp_path = f"{self.config_path}.tmp"
        try:
            with open(tmp_path, "w", encoding="utf-8") as f:
                f.writelines(lines)
                f.flush()
                os.fsync(f.fileno())

            os.replace(tmp_path, self.config_path)
            logger.info(f"Successfully committed all tool offsets to {self.config_path}")
        except Exception as ex:
            if os.path.exists(tmp_path):
                os.remove(tmp_path)
            raise ConfigManagerException(f"Failed to atomically write config: {ex}")

    def rollback(self) -> str:
        """
        Restores the newest timestamped backup copy.

        Returns:
            str: Name of the restored backup file.
        """
        pattern = f"{self.config_path}.calib_backup_*"
        backups = sorted(glob.glob(pattern))
        if not backups:
            raise ConfigManagerException("No historical backups found to restore.")

        latest_backup = backups[-1]
        shutil.copy2(latest_backup, self.config_path)
        logger.info(f"Restored configuration from: {latest_backup}")
        return latest_backup
