"""
Configuration Persistence & Backup Manager for Tool-Klipper-Calibration.

Safely saves calibrated tool offsets into an isolated tool_offsets.cfg file
using atomic temporary writes and automatic timestamped backups.
"""

from typing import Dict, List, Optional
import datetime
import glob
import logging
import os
import shutil

logger = logging.getLogger("tool_calibrator.config_manager")


class ConfigManagerException(Exception):
    """Raised when configuration operations fail."""
    pass


class ConfigManager:
    """
    Manages offset reading, atomic persistence, and historical rollbacks.
    """

    def __init__(self, config_file_path: str = "~/printer_data/config/tool_offsets.cfg") -> None:
        self.config_path = os.path.expanduser(config_file_path)
        self.max_backups = 10

    def create_backup(self) -> Optional[str]:
        """
        Creates a timestamped backup copy of tool_offsets.cfg if it exists.
        Automatically rotates and purges backups older than max_backups.
        """
        if not os.path.exists(self.config_path):
            return None

        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_filename = f"{self.config_path}.calib_backup_{timestamp}"
        try:
            shutil.copy2(self.config_path, backup_filename)
            logger.info(f"Created configuration backup: {backup_filename}")
            self._rotate_backups()
            return backup_filename
        except Exception as ex:
            logger.error(f"Failed to create configuration backup: {ex}")
            raise ConfigManagerException(f"Backup creation failed: {ex}")

    def _rotate_backups(self) -> None:
        """Keeps the most recent N backups and deletes older ones."""
        pattern = f"{self.config_path}.calib_backup_*"
        backups = sorted(glob.glob(pattern))
        if len(backups) > self.max_backups:
            to_remove = backups[:-self.max_backups]
            for old_backup in to_remove:
                try:
                    os.remove(old_backup)
                    logger.debug(f"Purged old backup: {old_backup}")
                except OSError:
                    pass

    def load_section(self, section_name: str) -> Dict[str, str]:
        """
        Loads key-value pairs from a specific section in tool_offsets.cfg.
        Returns an empty dict if the section or file does not exist.
        """
        if not os.path.exists(self.config_path):
            return {}

        clean_section = section_name.strip("[]")
        target_header = f"[{clean_section}]"
        results: Dict[str, str] = {}
        in_section = False

        with open(self.config_path, "r", encoding="utf-8") as f:
            for raw_line in f:
                line = raw_line.strip()
                if line.startswith("[") and line.endswith("]"):
                    in_section = (line == target_header)
                    continue

                if in_section and line and not line.startswith("#"):
                    if ":" in line:
                        k, v = line.split(":", 1)
                        results[k.strip()] = v.strip()
                    elif "=" in line:
                        k, v = line.split("=", 1)
                        results[k.strip()] = v.strip()

        return results

    def save_section(self, section_name: str, values: Dict[str, Any]) -> None:
        """
        Atomically updates or creates any [section_name] with key-value pairs.
        """
        self.create_backup()

        lines: List[str] = []
        if os.path.exists(self.config_path):
            with open(self.config_path, "r", encoding="utf-8") as f:
                lines = f.readlines()
        else:
            lines = [
                "# Tool-Klipper-Calibration Offsets File\n",
                "# Auto-generated by Tool-Klipper-Calibration\n",
                "# Include this in printer.cfg via: [include tool_offsets.cfg]\n\n"
            ]

        clean_section = section_name.strip("[]")
        target_header = f"[{clean_section}]"
        section_start = -1
        section_end = len(lines)

        for i, raw_line in enumerate(lines):
            line = raw_line.strip()
            if line == target_header:
                section_start = i
            elif section_start != -1 and line.startswith("[") and line.endswith("]"):
                section_end = i
                break

        formatted_values = {}
        for k, v in values.items():
            if isinstance(v, float):
                formatted_values[k] = f"{v:.3f}"
            else:
                formatted_values[k] = str(v)

        if section_start != -1:
            existing_keys = set()
            for idx in range(section_start + 1, section_end):
                line = lines[idx].strip()
                for key, val_str in formatted_values.items():
                    if line.startswith(f"{key}:") or line.startswith(f"{key}="):
                        lines[idx] = f"{key}: {val_str}\n"
                        existing_keys.add(key)

            missing_keys = [k for k in formatted_values if k not in existing_keys]
            if missing_keys:
                insert_lines = [f"{k}: {formatted_values[k]}\n" for k in missing_keys]
                lines[section_end:section_end] = insert_lines
        else:
            new_block = [f"\n{target_header}\n"]
            for k, val_str in formatted_values.items():
                new_block.append(f"{k}: {val_str}\n")
            lines.extend(new_block)

        tmp_path = f"{self.config_path}.tmp"
        try:
            with open(tmp_path, "w", encoding="utf-8") as f:
                f.writelines(lines)
                f.flush()
                os.fsync(f.fileno())

            os.replace(tmp_path, self.config_path)
            logger.info(f"Successfully committed section {target_header} to {self.config_path}")
        except Exception as ex:
            if os.path.exists(tmp_path):
                os.remove(tmp_path)
            raise ConfigManagerException(f"Failed to atomically write config: {ex}")

    def save_tool_offsets(self, tool_number: int, offsets: Dict[str, float]) -> None:
        """
        Atomically updates or creates the [tool N] section with new gcode offsets.
        """
        offset_strings = {}
        for axis, val in offsets.items():
            offset_strings[f"gcode_{axis.lower()}_offset"] = val

        self.save_section(f"tool {tool_number}", offset_strings)

    def rollback(self) -> str:
        """
        Restores the newest timestamped backup copy.

        Returns:
            str: Name of the restored backup file.
        """
        pattern = f"{self.config_path}.calib_backup_*"
        backups = sorted(glob.glob(pattern))
        if not backups:
            raise ConfigManagerException("No historical backups found to restore.")

        latest_backup = backups[-1]
        shutil.copy2(latest_backup, self.config_path)
        logger.info(f"Restored configuration from: {latest_backup}")
        return latest_backup
